resolver: lts-14.27
compiler: ghcjs-8.6.0.1

packages:
- .

extra-deps:
- miso-1.7.1.0

allow-newer: true

setup-info:
  ghcjs:
    source:
      ghcjs-8.6.0.1:
        url: "https://github.com/ghcjs/ghcjs/releases/download/v8.6.0.1/ghcjs-8.6.0.1.tar.gz"